### ISSUE TITLE
好像不支持https登录

### ISSUE THREAD

**Issue by silence9527** [cikezhu/PwaBrowser#1]
之前是http，今天上传证书用https之后就400咯

**Comment by cikezhu** [comment]
支持的呀, 我就是用https登录的

**Comment by silence9527** [comment]
> 

芜湖，我是第一个issue，app很好用啦，感谢大佬，https的话在输入网址界面得手动带上https://，建议左边加个选择框，可以选择http还是https

**Comment by cikezhu** [comment]
就首次输入而已, 懒得写一个选择框了~哈哈  如果有人可以提pr也行
